### ISSUE TITLE
Feature request: Pathlib support

### ISSUE THREAD

**Issue by mwtoews** [corteva/geocube#78]
#### Summary
This is a feature request to better integrate [pathlib](https://docs.python.org/3/library/pathlib.html) objects to avoid surprises and confusion.

#### Code Sample

```python
import xarray as xr
from geocube.api.core import make_geocube
from pathlib import Path

base_dir = Path("C:/dir/to/data")
raster_fname = base_dir / "Mana.tif"
polys_fname = base_dir / "Mana_polygons.shp"

xds = xr.open_rasterio(raster_fname )

cube = make_geocube(polys_fname, like=xds)

```
#### Problem description

Shows error from last command:
```
Traceback (most recent call last):

  File "C:\Users\mtoews\AppData\Local\Temp/ipykernel_16964/1127047227.py", line 10, in <module>
    cube = make_geocube(polys_fname, like=xds)

  File "C:\Users\mtoews\Miniconda3\envs\pyforge\lib\site-packages\geocube\api\core.py", line 90, in make_geocube
    return VectorToCube(

  File "C:\Users\mtoews\Miniconda3\envs\pyforge\lib\site-packages\geocube\vector_to_cube.py", line 68, in __init__
    self._vector_data = load_vector_data(vector_data)

  File "C:\Users\mtoews\Miniconda3\envs\pyforge\lib\site-packages\geocube\geo_utils\geobox.py", line 73, in load_vector_data
    vector_data = geopandas.GeoDataFrame(vector_data)

  File "C:\Users\mtoews\Miniconda3\envs\pyforge\lib\site-packages\geopandas\geodataframe.py", line 122, in __init__
    super().__init__(data, *args, **kwargs)

  File "C:\Users\mtoews\Miniconda3\envs\pyforge\lib\site-packages\pandas\core\frame.py", line 730, in __init__
    raise ValueError("DataFrame constructor not properly called!")

ValueError: DataFrame constructor not properly called!
```

#### Expected Output

Naïvely expected `make_geocube` to handle a pathlib object. To be fair, the docstring has:
> vector_data: str or geopandas.GeoDataFrame
> A file path to an OGR supported source or GeoDataFrame containing the vector data.

A workaround is to either use `os.fspath(polys_fname)` or `str(polys_fname)` to convert to str for vector_data.

#### Environment Information

 - `python -c "import geocube; geocube.show_versions()"`
```
geocube v0.0.18

GDAL deps:
         fiona: 1.8.20
   GDAL[fiona]: 3.3.2
      rasterio: 1.2.10
GDAL[rasterio]: 3.3.2

Python deps:
       appdirs: 1.4.4
         click: 8.0.3
      datacube: 1.8.6
     geopandas: 0.10.2
     rioxarray: 0.8.0
        pyproj: 3.2.1
        xarray: 0.19.0

System:
        python: 3.9.7 | packaged by conda-forge | (default, Sep 29 2021, 19:15:42) [MSC v.1916 64 bit (AMD64)]
    executable: C:\Users\mtoews\Miniconda3\envs\pyforge\python.exe
       machine: Windows-10-10.0.17134-SP0
```
#### Installation method
 - conda

#### Conda environment information

<details>

```
$ conda list  (selective)"
datacube                  1.8.6              pyhd8ed1ab_0    conda-forge
fiona                     1.8.20           py39hea8b339_2    conda-forge
gdal                      3.3.2            py39h7c9a9b1_4    conda-forge
rasterio                  1.2.10           py39h20dd13d_0    conda-forge
rioxarray                 0.8.0              pyhd8ed1ab_0    conda-forge
scipy                     1.7.1            py39hc0c34ad_0    conda-forge
xarray                    0.19.0             pyhd8ed1ab_1    conda-forge
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info
     active environment : pyforge
    active env location : C:\Users\mtoews\Miniconda3\envs\pyforge
            shell level : 2
       user config file : C:\Users\mtoews\.condarc
 populated config files : C:\Users\mtoews\.condarc
                          C:\Users\mtoews\Miniconda3\envs\pyforge\.condarc
          conda version : 4.10.3
    conda-build version : not installed
         python version : 3.9.7.final.0
       virtual packages : __cuda=7.5=0
                          __win=0=0
                          __archspec=1=x86_64
       base environment : C:\Users\mtoews\Miniconda3  (writable)
      conda av data dir : C:\Users\mtoews\Miniconda3\etc\conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\mtoews\Miniconda3\pkgs
                          C:\Users\mtoews\.conda\pkgs
                          C:\Users\mtoews\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\mtoews\Miniconda3\envs
                          C:\Users\mtoews\.conda\envs
                          C:\Users\mtoews\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.10.3 requests/2.26.0 CPython/3.9.7 Windows/10 Windows/10.0.17134
          administrator : False
             netrc file : None
           offline mode : False
```
</details>

**Comment by snowman2** [comment]
Related: https://github.com/geopandas/geopandas/issues/1323
Place to update code: https://github.com/corteva/geocube/blob/f75ac98385ec79bc364e5f27dcc4fb5b1ca1a938/geocube/geo_utils/geobox.py#L70

Something like this should do it:
```python
import io
from pathlib import Path
...
if isinstance(vector_data, (str, Path, io.TextIOBase))
```
