### ISSUE TITLE
make_geocube shows confusing error: AttributeError: 'NoneType' object has no attribute '__geo_interface__'

### ISSUE THREAD

**Issue by mwtoews** [corteva/geocube#79]
#### Summary
This issue seems to occur with a large dataset, where it is not clear what the main issue is in the error trace.

#### Code Sample

```python
import xarray as xr
from geocube.api.core import make_geocube
from pathlib import Path

base_dir = Path("C:/dir/to/data")
raster_fname = base_dir / "Big.tif"
polys_fname = base_dir / "Big_polygons.shp"

xds = xr.open_rasterio(raster_fname)

cube = make_geocube(str(polys_fname), like=xds)

```
#### Problem description

From the last command, a warning is first shown (this is an unreported xarray issue, see `xds.crs` later in report):
```
C:\Users\mtoews\Miniconda3\envs\pyforge\lib\site-packages\pyproj\crs\crs.py:131: FutureWarning: '+init=<authority>:<code>' syntax is deprecated. '<authority>:<code>' is the preferred initialization method. When making the change, be mindful of axis order changes: https://pyproj4.github.io/pyproj/stable/gotchas.html#axis-order-changes-in-proj-6
  in_crs_string = _prepare_from_proj_string(in_crs_string)
```
followed by an error trace:
```
Traceback (most recent call last):

  File "C:\Users\mtoews\AppData\Local\Temp/ipykernel_23028/741645946.py", line 13, in <module>
    cube = make_geocube(str(polys_fname), like=xds)

  File "C:\Users\mtoews\Miniconda3\envs\pyforge\lib\site-packages\geocube\api\core.py", line 90, in make_geocube
    return VectorToCube(

  File "C:\Users\mtoews\Miniconda3\envs\pyforge\lib\site-packages\geocube\vector_to_cube.py", line 163, in make_geocube
    return self._get_dataset(

  File "C:\Users\mtoews\Miniconda3\envs\pyforge\lib\site-packages\geocube\vector_to_cube.py", line 238, in _get_dataset
    grid_array = self._get_grid(

  File "C:\Users\mtoews\Miniconda3\envs\pyforge\lib\site-packages\geocube\vector_to_cube.py", line 345, in _get_grid
    image_data = self._rasterize_function(

  File "C:\Users\mtoews\Miniconda3\envs\pyforge\lib\site-packages\geocube\rasterize.py", line 79, in rasterize_image
    zip(geometry_array.apply(mapping).values, data_values),

  File "C:\Users\mtoews\Miniconda3\envs\pyforge\lib\site-packages\geopandas\geoseries.py", line 624, in apply
    result = super().apply(func, convert_dtype=convert_dtype, args=args, **kwargs)

  File "C:\Users\mtoews\Miniconda3\envs\pyforge\lib\site-packages\pandas\core\series.py", line 4357, in apply
    return SeriesApply(self, func, convert_dtype, args, kwargs).apply()

  File "C:\Users\mtoews\Miniconda3\envs\pyforge\lib\site-packages\pandas\core\apply.py", line 1043, in apply
    return self.apply_standard()

  File "C:\Users\mtoews\Miniconda3\envs\pyforge\lib\site-packages\pandas\core\apply.py", line 1098, in apply_standard
    mapped = lib.map_infer(

  File "pandas\_libs\lib.pyx", line 2859, in pandas._libs.lib.map_infer

  File "C:\Users\mtoews\Miniconda3\envs\pyforge\lib\site-packages\shapely\geometry\geo.py", line 205, in mapping
    return ob.__geo_interface__

AttributeError: 'NoneType' object has no attribute '__geo_interface__'
```

As for the inputs:
```
>>> xds
<xarray.DataArray (band: 1, y: 3466, x: 2400)>
[8318400 values with dtype=float64]
Coordinates:
  * band     (band) int32 1
  * y        (y) float64 6.234e+06 6.234e+06 6.233e+06 ... 5.368e+06 5.368e+06
  * x        (x) float64 1.492e+06 1.492e+06 1.493e+06 ... 2.092e+06 2.092e+06
Attributes:
    transform:         (250.0, 0.0, 1492000.0, 0.0, -250.0, 6234000.0)
    crs:               +init=epsg:2193
    res:               (250.0, 250.0)
    is_tiled:          1
    nodatavals:        (nan,)
    scales:            (1.0,)
    offsets:           (0.0,)
    AREA_OR_POINT:     Area
    TIFFTAG_SOFTWARE:  MATLAB 9.7, Mapping Toolbox 4.9
>>> import geopandas
>>> polys = geopandas.read_file(polys_fname)
>>> polys.shape
(47772, 5)
>>> polys.dtypes
reach        int64
down         float64
order          int64
rids          object
geometry    geometry
dtype: object
```
Approximately half of the polygons cover the raster.

#### Expected Output

Expected `make_geocube` to work without issue, or provide a better error message for the underling issue.

#### Environment Information

 - `python -c "import geocube; geocube.show_versions()"`
```
geocube v0.0.18

GDAL deps:
         fiona: 1.8.20
   GDAL[fiona]: 3.3.2
      rasterio: 1.2.10
GDAL[rasterio]: 3.3.2

Python deps:
       appdirs: 1.4.4
         click: 8.0.3
      datacube: 1.8.6
     geopandas: 0.10.2
     rioxarray: 0.8.0
        pyproj: 3.2.1
        xarray: 0.19.0

System:
        python: 3.9.7 | packaged by conda-forge | (default, Sep 29 2021, 19:15:42) [MSC v.1916 64 bit (AMD64)]
    executable: C:\Users\mtoews\Miniconda3\envs\pyforge\python.exe
       machine: Windows-10-10.0.17134-SP0
```
#### Installation method
 - conda

#### Conda environment information

<details>

```
$ conda list  (selective)"
datacube                  1.8.6              pyhd8ed1ab_0    conda-forge
fiona                     1.8.20           py39hea8b339_2    conda-forge
pyproj                    3.2.1            py39h39b2389_2    conda-forge
gdal                      3.3.2            py39h7c9a9b1_4    conda-forge
rasterio                  1.2.10           py39h20dd13d_0    conda-forge
rioxarray                 0.8.0              pyhd8ed1ab_0    conda-forge
scipy                     1.7.1            py39hc0c34ad_0    conda-forge
xarray                    0.19.0             pyhd8ed1ab_1    conda-forge
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info
     active environment : pyforge
    active env location : C:\Users\mtoews\Miniconda3\envs\pyforge
            shell level : 2
       user config file : C:\Users\mtoews\.condarc
 populated config files : C:\Users\mtoews\.condarc
                          C:\Users\mtoews\Miniconda3\envs\pyforge\.condarc
          conda version : 4.10.3
    conda-build version : not installed
         python version : 3.9.7.final.0
       virtual packages : __cuda=7.5=0
                          __win=0=0
                          __archspec=1=x86_64
       base environment : C:\Users\mtoews\Miniconda3  (writable)
      conda av data dir : C:\Users\mtoews\Miniconda3\etc\conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\mtoews\Miniconda3\pkgs
                          C:\Users\mtoews\.conda\pkgs
                          C:\Users\mtoews\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\mtoews\Miniconda3\envs
                          C:\Users\mtoews\.conda\envs
                          C:\Users\mtoews\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.10.3 requests/2.26.0 CPython/3.9.7 Windows/10 Windows/10.0.17134
          administrator : False
             netrc file : None
           offline mode : False
```
</details>

**Comment by snowman2** [comment]
From the error message, it appears that one of the geometries is None. You should be able to filter it out by loading the shapefile in geopandas and removing the null geometries and passing the geodataframe to make_geocube.

Also, are you able to provide a minimal example set of input files to re-produce the issue?

**Comment by snowman2** [comment]
This is related to #9

**Comment by snowman2** [comment]
Mind humoring me and trying this:
```python
cube = make_geocube(polys[~pandas.isnull(polys.geometry)], like=xds)
```
